[project]
name = "pytoolconfig"
version = "0.1.0"
description = ""
authors = [
    {name = "bageljr", email = "bageljr897@protonmail.com"},
]
license-expression = "LGPL-3.0-or-later"
dependencies = [
    "tomli>=2.0",
    "pydantic>=1.7.4",
    "typing-extensions>=4.1.1",
]
requires-python = ">=3.7"

[project.urls]
Homepage = ""

[project.optional-dependencies]
global = [
    "appdirs>=1.4.4",
]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.0.1",
]
[tool.pytoolconfig]
formatter = "black"

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
