name: Pre-commit

on:
  - push
  - pull_request

jobs:
  pre-commit:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.11
          enable-pep582: true
      - name: Install dependencies
        run: |
          pdm install
      - uses: pre-commit/action@v3.0.0
